version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '01:00'
      timezone: 'Europe/London'
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    groups:
      npm-security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
      npm-dependencies:
        applies-to: 'version-updates'
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # cause a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-deps
      prefix-development: chore(dev-deps)
    ignore:
      - dependency-name: '@salesforce/dev-scripts'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
